name: Deploy static snapshot to GitHub Pages (JSON flow)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ne-leg-bill-summaries-json

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: python -m pip install -U requests beautifulsoup4

      - name: Run Python ETL (writes data/bills.json)
        run: python scripts/etl.py
        env:
          OPENSTATES_API_KEY: ${{ secrets.OPENSTATES_API_KEY }}
          SESSION_IDENTIFIER: "2025"
          ETL_LOOKBACK_DAYS: "7"
          NE_REQUEST_DELAY_MS: "0.5"

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ⬇⬇ change this from "npm ci" to "npm install"
      - run: npm install
      - run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
